services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: astral_gate_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - astral_gate_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: astral_gate_backend
    environment:
      DATABASE_URL: host=${HOST} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable

    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ${PATH_TO_KEYSTORES}:/app/keystores

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: astral_gate_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  astral_gate_db_data:

networks:
  app-network:
    driver: bridge